##
#   Database Settings
###
spring:
  datasource:
    #url: jdbc:sqlite:nasic.db
    url: jdbc:h2:./results.db;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    platform: h2
    username: sam
    password: password
    driverClassName: org.h2.Driver
  jpa:
    #database-platform: com.davis.csv.editor.config.SQLiteDialect
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    properties:
      hibernate:
        show_sql: false
    #    use_sql_comments: true
    #    format_sql: true

###
#   H2 Settings
###
  h2:
    console:
      enabled: true
      path: /h2
      port: 9999
      settings:
        trace: false
        web-allow-others: false

